pipeline:
  name: "stesting "
  identifier: stesting
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: rn
        build: <+input>
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: dockerconnector
                    image: node:20-alpine
                    shell: Sh
                    command: |-
                      ls -l 
                      cd frontend 
                      docker build -t frontend .
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: d
              namespace: test
              automountServiceAccountToken: true
              nodeSelector: {}
              harnessImageConnectorRef: dockerconnector
              os: Linux
